# -*- coding: utf-8 -*-
"""PythonBasics

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wDH2QmYpHus-D5SMAMKD7anqkS_OH_e3
"""

# Wap to find given number is positive or negative
a = int(input("Give the input number:"))
if (a >= 0):
   print("the given number is positive")
if (a < 0):
   print("the given number is negative")

# Wap to find given number is positive or negative
a = int(input("Give the input number:"))
if (a >= 0):
   print("the given number is positive")
else:
   print("the given number is negative")

#Wap  to find whether given number is even or odd
#give the input value
a = int(input("the given input is:"))
#to define if its even it should be divisible by 2 and remainder should be 0
if ((a%2)==0):
  print("the number is even")
#else the number is odd if its not divisible by 2 and remainder is not 0
else:
  print("the number is odd")

a = int(input("the given input is:"))
#to define if its odd it should not be divisible by 2 and remainder should not be 0
if ((a%2)!=0):
  print("the number is odd")
#else the number is even if its  divisible by 2 and remainder is  0
else:
  print("the number is even")

# WAP to check whether given number is +ve/-ve and even/odd
#firstly assigning the value to be given
a= int(input("the input value is:"))
#then defining the value is positive and negative at the same time
if (a >= 0):
   print("the given number is positive")
else:
   print("the given number is negative")
#to check whether the given number is even or odd
#to define if its even it should be divisible by 2 and remainder should be 0
if ((a%2)==0):
  print("the number is even")
#else the number is odd if its not divisible by 2 and remainder is not 0
else:
  print("the number is odd")

a = int(input("Give me an input: "))  #3
if ((a>=0)  and ((a%2)==0)):
    print('Positive even')
elif ((a>=0) and ((a%2)!=0)):
    print('positive odd ')

elif ((a<0)  and ((a%2)==0)):
    print('negative even')
else:
    print('negative odd')

a = int(input("Give me an input: "))
if (a.alpha() == False):
   a = int(a)
    if((a>=0)  and ((a%2)==0)):
        print('Positive even')
    elif ((a>=0) and ((a%2)!=0)):
        print('positive odd ')

    elif ((a<0)  and ((a%2)==0)):
        print('negative even')
    elif ((a<0) and ((a%2)!=0)):
        print('negative odd')
else:
     print("none of these")

#filtering
# Find where the given number lies ?
# 0-10, 10-20, 20-30, more than 30?
a = input("Give me an input: ") #3
if (a.isdigit() == True):
   a= int(a)
   if (a<=10):
      print("the given number belongs in the range 0-10")
   elif (a<=20):
      print("the given number belongs in the range 10-20")
   elif (a<=30):
      print("the given number belongs in the range 20-30")
   elif (a>30):
      print("the given number belongs in the range more than 30")
else:
    print("the input must be a number")

#range
a = int(input("Give me an input: "))
if (a in range(0,10)):
   print("its in range 0-10")
elif (a in range(10,20)):
   print("its in range 10-20")
elif (a in range(20,30)):
   print("its in range 20-30")
else:
   print("its more than 30")

#and
a = int(input("Give me an input: "))
if ((a>0) and (a<=10)):
   print("its in range 0-10")
elif ((a>10) and (a<=20)):
   print("its in range 10-20")
elif ((a>20) and (a<=30)):
   print("its in range 20-30")
else:
   print("its more than 30")

#< <
a = input("Give me an input: ")
if (a.isdigit() == True):
   a= int(a)
   if (0<a<=10):
      print("the given number belongs in the range 0-10")
   elif (10<a<=20):
      print("the given number belongs in the range 10-20")
   elif (20<a<=30):
      print("the given number belongs in the range 20-30")
   elif (a>30):
      print("the given number belongs in the range more than 30")
else:
    print("the input must be a number")

# if a number is multiple of 3  but not 5, print "fizz"
# if a number is multiple of 5  but not 3, print "buzz"
# if a number is multiple of both print "fizz buzz"
# If a number is not a multiple of both then "not a fizz buzz"?
a = int(input("Give me an input: "))
if (((a%3) ==0) and ((a%5)!=0)):
  print("fizz")
elif(((a%5) ==0) and ((a%3)!=0)):
  print("buzz")
elif(((a%5)==0) and ((a%3)==0)):
  print("fizz buzz")
else:
  print("not a fizz buzz")

# WAP to find the square root of the given value?
a = int(input("Give me an input: "))
if ((a)**(1/2)):
  print(f"the value of root is:{(a)**(1/2)}")

# WAP to calculate the area and perimeter of polygons(triangle, square, rectangle,circle)?
pi=3.14
r=int(input("the radius of the circle is:"))
if (pi*(r**2)):
  print(f"the area of the circle is:{(pi*(r**2))}")
if (2*pi*r):
  print(f"the perimeter of the circle is:{(2*pi*r)}")

# WAP to calculate the area and perimeter of polygons(triangle, square, rectangle,circle)?
#square
s=int(input("the value of side is:"))
# if((s*s)and (4*s)):
print(f"Area of square:{(s*s)}")
print(f"perimeter of square:{(4*s)}")

# WAP to calculate the area and perimeter of polygons(triangle, square, rectangle,circle)?
#Rectangle
l=int(input("the lenght of rectangle is:"))
b=int(input("the breadth of rectangle is:"))
print(f"area of rectangle:{(l*b)}")
print(f"perimeter of rectangle:{(2*(l+b))}")

# WAP to calculate the area and perimeter of polygons(triangle, square, rectangle,circle)?
#triangle
a=int(input("first side of triangle:"))
b=int(input("second side of triangle:"))
c=int(input("third side of triangle:"))
h=int(input("height of triangle:"))
print(f"the perimeter of triangleis:{a+b+c}")
print(f"the area of triangleis:{(1/2)*b*h}")

# WAP to classify the amount and the quality of the purchase?
# NOTE: Consider every product is of same cost.
# Price = your_value
# quantity  = your_value
# amount = price * quantity

# amount =  ( 0 - 500 ) is low quality
# amount =  ( 501 - 1000 )is High quality
# amount =  ( 100 - 200 ) is cheaper cost
# amount =  ( 201 - 400 ) is good cost
# amount =  ( 401 - 800 ) is moderate cost
# amount =  ( 801 - 1000 )is costly
p=int(input("Price:"))
q=int(input("Quantity:"))
a=int(p*q)
#a=amount
if(a in range(0,500)):
 print("It is low quality")
elif(a in range(501,1001)):
 print("It is high quality")
elif(a in range(100,201)):
 print("It is cheaper quality")
elif(a in range(200,401)):
 print("It is good cost")
elif(a in range(401,801)):
 print("It is moderate cost")
elif(a in range(801,1001)):
 print("It is costly")
else:
 print("Invalid amount")

# WAP to classify the amount and the quality of the purchase?
# NOTE: Consider every product is of same cost.
# Price = your_value
# quantity  = your_value
# amount = price * quantity

# amount =  ( 0 - 500 ) is low quality
# amount =  ( 501 - 1000 )is High quality
# amount =  ( 100 - 200 ) is cheaper cost
# amount =  ( 201 - 400 ) is good cost
# amount =  ( 401 - 800 ) is moderate cost
# amount =  ( 801 - 1000 )is costly
p=int(input("price of product:"))
q=int(input("quantity:"))
a=int(p*q)
if (a>=0)and(a<=500):
  print("its of low quality")
elif(a>=501)and (a<=1000):
  print("its of higher quality")
else:
  print("error")
if (a>=100)and(a<=200):
  print("cheaper cost")
elif(a>=201)and (a<=400):
  print("good cost")
elif(a>=401)and (a<=800):
  print("moderate cost")
elif(a>=801)and (a<=1000):
  print("costly")

# Check whether a triangle is a scalene/isosceles/equilateral triangle?
a=int(input("the first side of triangle is:"))
b=int(input("the second side of triangle is:"))
c=int(input("the third side of triangle is:"))
if ((a==b) and (b==c)and(c==a)):
  print("this is equilateral triangle")
elif((a==b)or (b==c) or (c==a)):
  print("this is an isosceles triangle")
else:
  print("this is an scalane triangle")

#another format
a=int(input("the first side of triangle is:"))
b=int(input("the second side of triangle is:"))
c=int(input("the third side of triangle is:"))
if ((a==b) and (b==c)and(c==a)):
  print("this is equilateral triangle")
elif((a!=b)and (b!=c) and (c!=a)):
  print("this is an scalane triangle")
else:
  print("this is an isosceles triangle")

# Any product costs 100 each in shopping mall
# There is a discount of 10% on the bill if customer shops more than 1000 rupees
# Hint- Ask user, how many products he purchased as input to your code.
# Tell the customer the final bill.
a=int(input("total number of products purchased is:"))
t=int(a*100)
if(t):
  print(f"the final bill is:{t}")
  if(t>1000):
    d=int(t*(10/100))
    print(f"Final bill After discount:{d}")
else:
  print("no products purchased")

# students above 75% attendance should be allowed for exam
# students with permission are allowed though less than 75%
a=int(input("student attendance:"))
if (a>=75):
  print("the student is allowed for exam")
elif(a<75):
    p=str(input("Status of student:")) #"student with permission allowed"
    if(p=="permission granted"):
       print("student with permission allowed for exam")
    elif(p!= "permission granted"):
       print("student not allowed for exam")
else:
  print("Invalid attendance")

#alternative
a=int(input("the total number of classes:"))
b=int(input("the number of classes present:"))
if (((b/a)*100)>=75):
  print("the student is allowed for the exam")
elif(((b/a)*100)<75):
  p=str(input("is their permission granted:yes/no-"))
  if(p=="yes"):
    print("student allowed for the exam")
  else:
    print("student not allowed for exam")

#quadratic equation
# WAP to find the Roots  of the Quadratic equation?
# WAP to find the Nature of the roots along with the above?
a= int(input("the coefficient of x2:"))
b= int(input("the coefficient of x:"))
c= int(input("the constant value is:"))
n=((b**2)-(4*a*c))
d=(2*a)
if (n>0):
  r1=(-b+(n**0.5))/d
  r2=(-b-(n**0.5))/d
  print("real roots")
  print("root1",r1)
  print("root2",r2)
elif(n==0):
  print("equal roots")
  print("root1=",-b/d)
  print("root2=",-b/d)
else:
  print("imaginary roots")