# -*- coding: utf-8 -*-
"""PYTHON_ASSESSMENT

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nsiqt3ObMUQ306xSCKuCGFRmwP-mJgyJ

#PYTHON ASSESSMENT:
"""

#1. a
p,s = 9,8
# p *= s ?
p*=s #p=p*s;9*8;72
print(p)

#1.b
p,s= 9,8
# p -= s ?
p-=s #p=p-s; 9-8;1
print(p)

#1.c
p,s= 9,8
# p /= s ?
p/=s #p=p/s; 9/8;1.125
print(p)

p,s= 9,8
# p >>= s ?
p>>=s #p=p>>s; 9>>8;0
print(p)

p,s= 9,8
# p <<= s ?
p<<=s #p=p<<s; 9<<8;2304
print(p)

#Example of a multiline comment?

# this is an example of
# multi line
# comment

#3.
S, t = 3, 4
#S %= t ?
S%=t #S=S%t;3%4;3
print(S)

#4.
A=8
B = 10
#A&B ?
A&B #8&10;1000&1010;1000

#5.Command to find the length of the string?
a="hi there,great going"
len(a)

#6. Which of the following is an invalid identifier?
# a. a123 -valid
# b. _n_9 -valid
# c. All_is_well -valid
# d. aB1! -invalid

import keyword
n=input()
a='~!@#$%^&*()-=+?><./|\?,:;"\''
if(n in ord()):
  print('invalid')

#7. Give an example for each of these for a 4 words sentence -
#Title Case
"You Are Good Coder"
#CamelCase
"youAreGoodCoder"
#SnakeCase
"you_are_good_coder"

#8.
a, b , c = 1, 2, 3
#What is the output for b*(c+a) ?
b*(c+a) #2*(3+1);2*4;8

#9.
str1 =' how are you'
#Print ‘are’ only
str1[5:8]

#10. Write the command to get only imaginary number in the code below?
import cmath
x = 5
y = 5
z = complex(x,y)
print(z)#(5+5j)
print(z.real,z.imag)
print(z.imag)#imaginary number

#11.
#bool( { } )?
bool({})#false;empty set

#11.
#bool(False)?
bool(False)#False

#12.What are the data types of follwing respectively?
#a.(1,[2,3])
a=(1,[2,3])
type(a)#its a tuple as its enclosed in paranthesis

#b. [1,2,'f']
a=[1,2,'f']
type(a)#enlosed in [] is list

#c.'hey1'
a='hey1'
type(a)#enclosed in '' is string

#d.123
a=123
type(a)#its integer

#e.{ (1,2),['e'] }
a={(1,2),['e']}
type(a)#list data type is not allowed in set

#13. What is the output for the code below?
print(10 == 9)#False as (10!=9);

#14. What is the output for the below code?
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))#quantity, itemno, price;(0,1,2);{49.95},{3},{567}

# #15.
# Convert the words ‘miss’ and ‘python’ to ‘mam’ and ‘C’ respectively without redeclaring the string?
Str2 = 'hey miss! Welcome to python'
Str2=Str2.replace('miss','mam')
Str2=Str2.replace('python','C')
print(Str2)

#16. Convert the string to title case and lower case?
Str3 = 'HYderabaD'
tc=Str3.title()
lc=Str3.lower()
print("Title case:",tc)
print("Lower case:",lc)

#17. Print how many number of ‘ A ‘ / ‘ a ‘ are there in the string without counting manually?
Str4 ='All apples are red in color and round in shape'
A=Str4.count('A')#counts the number of times A appears in string
a=Str4.count('a')#counts the number of times a appears in string
print(A)
print(a)

#18.What is the output for the code below?
x = {1,2,3,4,5}
y = {4,5,6,7,8}
#print(x+y)?
#print(x+y)-typeerror (unsupported operand '+'for set)
print(x.union(y))#we can use the union method to add two sets as an alternative

#19.
x = {1,2,3,4,5}
y = {4,5,6,7,9}
#print( x | y ) ?
print( x | y )#same elements or duplicates are excluded for'|'operator as its union of both

#20.What are the outputs for the code below?
print(0 | True)#0|1;1
print(0 == True)#0!=True;False
print('19' == 19 )#string != int;different datatypes

#21.Write a python code to add first n numbers?
n=int(input("enter till what number you wanna add :"))
result=0
i=1
while(i<=n):
  result=result+i
  i+=1
print(f"sum of n numbers is {result}")

#22.Write a code to loop over the items in fruits list?
fruits = ["apple", "orange", "kiwi"]
for f in fruits:
  print(f)

#23.Write a python code to print 6 table using for and while loop?
#while
a=int(input("give the number:"))
i=1
while(i<=10):
  print(f"{a}x{i}={a*i}")
  i+=1

#for
n=int(input("enter the number:"))
for i in range(1,11):
  print(f"{n}x{i}={n*i}")

#24.Write a command to get the value of this 6^4 ?
value=6**4
print(value)

"""25.What are the outputs for the code below?"""

for x in [1, 2, 3]:
   print(x-1)

"""26.What is the output of print
`tuple[0] if tuple = ( 'abcd', 786 , 2.23, 'john', 70.2 )`?
"""

tuple=('abcd', 786 , 2.23, 'john', 70.2 )
print(tuple[0])

"""27.What is the output of L[-2] if L = [1,2,3]?"""

L = [1,2,3]
output=L[-2]
print(output)

"""28.What will be the output of the below given code?"""

colors =['white','Black','Grey']
x='Red' not in colors
print(x)

"""29.Which is mutable and immutable in List and Tuple?

   **List:**

> List is mutable.
*   You can add, remove ,modify elements.
*    you can change , modify the content as well order of elements.

   **Tuple:**
> Tuple is immutable.
*  you can't change the size or order of elements.
* You cannnot add, remove ,modify elements.






   




"""

#list
a=[1,2,3,4]
a[1]=5
print(a)

#tuple
a=(1,2,3,4)
a[1]=5#typeerror as its immutable

"""30.What is the output of tiny * 3, if tiny = [123, 'john'] ?"""

tiny=[123,'john']
t=tiny*3
print(t)

"""31.Which is the function to check in a string that all characters are alphanumeric?
*  'isalnum' is used to check that characters are
alphanumeric
"""

string='thisisalphanumeric12'
a=string.isalnum()#considers alphabets and numbers(without spaces ,special characters,)
print(a)

string='this_isalphanumeric 2'
a=string.isalnum()
print(a)

"""32.What is the command line to get the output as ‘heshewe’?

```
a = ['he', 'she', 'we']
```


"""

a = ['he', 'she', 'we']
x="".join(a)
print(x)

"""*33*.L = [ 1, 2, 1,[3], 5 ]
What is the position of number 3?

"""

L =[ 1, 2, 1,[3], 5 ]
L.index([3])

"""34.Calculate total number of 9 in the below given list? And State the predefined function to
calculate number of 9?
List1 = [9, 90, 99, 999, 9999]
"""

List1 = [9, 90, 99, 999, 9999]
List1=List1.count(9)
print(List1)

"""35.What is the result of this code?
```
nums = [10, 9, 8, 7, 6, 5]
nums[0] = nums[1] - 5
if 4 in nums: print(nums[3])
else: print(nums[4])
```



"""

nums = [10, 9, 8, 7, 6, 5]
nums[0] = nums[1] - 5
if 4 in nums: print(nums[3])
else: print(nums[4])

"""36.What is the result of this code?
```
nums = [9, 8, 7, 6, 5]
nums.append(4)
nums.insert(2, 11)
print(len(nums))
```



"""

nums = [9, 8, 7, 6, 5]
nums.append(4)
nums.insert(2, 11)
print(len(nums))

"""37.What is the result of this code?
```
list = [1, 1, 2, 3, 5, 8, 13]
print(list[list[4]])
```



"""

list = [1, 1, 2, 3, 5, 8, 13]
print(list[list[4]])

"""38.Which of the following is false statement in python?
```
a. int(144)==144 #True
b. int('144')==144 #True
c. int(144.0)==144 #True
d. None of the above

```


> Ans: d. None of the above

39.What is the output of [ 1, 2, 3 ] + [ 4, 5, 6 ] ?
"""

[ 1, 2, 3 ] + [ 4, 5, 6 ]

"""40.What is the command to sort a list?


*  sort() method can be used to sort a list in-place #ascending order
*  sort(reverse=True)#descending order sorting of list


"""

a=[40,70,80,4,5,2,77,14.11,17]
a.sort()
print(a)

a=[40,70,80,4,5,2,77,14.11,17]
a.sort(reverse=True)
print(a)

"""41.Which of the following statements is used when a statement is required syntactically but
you do not want any command or code to execute?
a. break
b. continue
c. pass
d. None of the above.


> Ans:pass

*   Its often used as a placeholder for code that has not been writtern,when your not yet ready to implement code,but you want to retain the structure of program.








"""

#pass example
for a in range(0,10):
 if (a%2==0):
  pass
 else:
    print(a)

"""42. What is the result of this code?
```
tup = ("hi", "Python", 2)
print (type(tup))
print (tup)
print (tup[1:])
print (tup[0:1])
print (tup + tup)
print (tup * 3)
```
### tup[2] = "hi",what is the updated tup?
"""

tup = ("hi", "Python", 2)
print (type(tup))
print (tup)
print (tup[1:])
print (tup[0:1])
print (tup + tup)
print (tup * 3)

tup = ("hi", "Python", 2)
tup[2] = "hi" #Typeerror tuple doesnot support item type (immutable)

#tuple modify by changing into another data type
tup = ("hi", "Python", 2)
x_1=[(tup)]
x[2] = "hi"
print(x)

"""43.What is the result of this code?
```
# for x in range(21,5,-3):
    print(x)
```


"""

for x in range(21,5,-3):
  print(x)

"""44.What is the result of this code?
```

#for i in range(0,5):
print(i)
break;

```


"""

for i in range(0,5):
  print(i)
  break;

"""45.Program to check whether a number is even or not"""

n=int(input("give the number:"))
if(n%2==0):
  print(f"{n} is even")
elif(n%2!=0):
  print(f"{n} is odd")
else:
  print("enter a valid number")

"""46.Bring this output using loops.
```
#
1
22
333
4444
55555
```


"""

i=1
while(i<=5):
  j=1
  while(j<=i):
     print(i,end='')
     j+=1
  print()
  i+=1

i=1
while(i<=5):
  j=1
  while(j<=i):
    print(i,end='')
    j+=1
  print()
  i+=1

num=int(input("give the no."))
for i in range(1,num+1):
  if(num%i==0):
    print(i)

